language: cpp

env:
 - QT_SELECT=qt4
 - QT_SELECT=qt5

before_install:
 - sudo add-apt-repository --yes ppa:canonical-qt5-edgers/ubuntu1204-qt5
 - sudo apt-get update -qq
 - sudo apt-get install -qq libqtcore4 qt4-qmake libqt5core5 qt5-qmake qt5-default qtchooser

script:
 - qmake && make && ./QExpression
